# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [2]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [3]:
# Load data here
df=pd.read_csv('data/listings.csv', sep=',')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [8]:
# 1. How many listings are there with a price less than 100? 
listings = df.price < 100
df[listings].calculated_host_listings_count.count()
# df[listings]

22778

In [9]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.
# df_bk = df.neighbourhood_group == 'Brooklyn'
# df[df_bk].calculated_host_listings_count.count()

bk = df.neighbourhood_group == 'Brooklyn'
df_bk = df.groupby(bk)['calculated_host_listings_count'].count()
new_df = pd.DataFrame(df_bk)
new_df = new_df.reset_index()
new_df[new_df.neighbourhood_group == True].calculated_host_listings_count

1    18632
Name: calculated_host_listings_count, dtype: int64

In [12]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.
condition1 = df.neighbourhood_group == 'Brooklyn'
condition2 = df.price < 100
df[condition1&condition2].count()

id                                10473
name                              10469
host_id                           10473
host_name                         10468
neighbourhood_group               10473
neighbourhood                     10473
latitude                          10473
longitude                         10473
room_type                         10473
price                             10473
minimum_nights                    10473
number_of_reviews                 10473
last_review                        8239
reviews_per_month                  8239
calculated_host_listings_count    10473
availability_365                  10473
dtype: int64

In [13]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
hosts = ['Michael', 'David', 'John', 'Daniel']
show_hosts = df.host_name.isin(hosts)
df[show_hosts]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
52,16595,LOFT HAVEN ~ Six Windows ~ Bricks ~ Plants ~ Q...,64522,Daniel,Brooklyn,Williamsburg,40.70933,-73.96792,Entire home/apt,271,1,172,2020-07-14,1.44,1,365
201,61747,"Cozy, Brooklyn, Prospect Park Studio",299370,David,Brooklyn,Prospect-Lefferts Gardens,40.65979,-73.96180,Entire home/apt,91,14,97,2018-01-31,0.83,1,44
209,62903,Beautiful modern studio apartment in heart of NYC,306605,Daniel,Manhattan,Chelsea,40.74238,-73.99567,Entire home/apt,205,15,68,2019-12-14,0.67,2,89
220,64015,Prime East Village 1 Bedroom,146944,David,Manhattan,East Village,40.72807,-73.98594,Entire home/apt,200,3,0,NaN,NaN,1,0
260,74073,Food & Music Dream Apartment in Williamsburg,211877,Daniel,Brooklyn,Williamsburg,40.71113,-73.96054,Entire home/apt,187,30,90,2020-07-31,0.81,1,261
349,138216,Sunny and Spacious Designer's Home,674970,Michael,Brooklyn,Greenpoint,40.72212,-73.94254,Entire home/apt,100,6,9,2019-09-20,0.17,1,0
351,140133,Truly Amazing Oasis In The City,622866,Daniel,Brooklyn,Williamsburg,40.71363,-73.96019,Entire home/apt,255,3,172,2020-07-02,1.56,1,319
363,148201,NYC - Sunny Greenwich Village 1br,715807,John,Manhattan,Greenwich Village,40.72831,-74.00177,Entire home/apt,175,3,18,2013-05-31,0.16,1,0
402,167013,Spacious modern studio apartment in Manhattan,306605,Daniel,Manhattan,Chelsea,40.74342,-73.99483,Entire home/apt,205,10,3,2018-05-13,0.04,2,90
431,187986,Comfort at Crossroads of Downtown,904833,Daniel,Manhattan,Chelsea,40.73862,-73.99758,Entire home/apt,250,1,2,2015-08-28,0.02,1,0
434,189135,Hell's Kitchen Funky 80s Hideaway,179020,Michael,Manhattan,Hell's Kitchen,40.76311,-73.99388,Private room,104,1,101,2019-12-28,0.98,1,365
435,189181,Room in Chic Modern High Line Luxury- New!,912541,David,Manhattan,Chelsea,40.74695,-74.00454,Private room,282,4,1,2014-04-20,0.01,1,0
479,212544,Quiet One Bedroom in Park Slope,1096084,Daniel,Brooklyn,Gowanus,40.67688,-73.98590,Entire home/apt,100,7,9,2016-06-23,0.08,1,0
515,233189,NYC Studio in Heart of Times Square,1220414,Michael,Manhattan,Hell's Kitchen,40.76166,-73.99675,Entire home/apt,85,30,89,2020-03-14,0.83,1,153
520,234870,Private Room With GREAT Location,1229984,John,Queens,Long Island City,40.74581,-73.95295,Private room,75,2,65,2017-07-31,0.64,1,259
523,235951,Stylish Studio with exclusive Terrace,1236070,Daniel,Manhattan,Midtown,40.75348,-73.97065,Entire home/apt,135,30,143,2020-04-15,1.33,1,260
585,255637,"Prime Prospect Heights, Brooklyn",1343814,Michael,Brooklyn,Prospect Heights,40.67336,-73.96541,Private room,65,31,40,2020-08-08,0.43,1,0
589,257787,Heart of Williamsburg. Brand New.,1356046,Daniel,Brooklyn,Williamsburg,40.71408,-73.94890,Entire home/apt,89,18,272,2020-03-23,2.55,2,104
650,274257,Duplex on the Upper East Side-59th,1434224,Michael,Manhattan,Upper East Side,40.76321,-73.96435,Private room,72,3,16,2019-08-17,0.15,1,273
691,289037,"2BR in Cobble Hill, Brooklyn, NY",632334,Michael,Brooklyn,Carroll Gardens,40.68353,-73.99140,Entire home/apt,189,2,14,2019-09-08,0.16,1,0
745,318021,Room in Huge 1200sf W Harlem Suite,1632149,Michael,Manhattan,Harlem,40.80343,-73.95310,Private room,110,3,56,2020-02-03,0.59,1,331
824,396636,Stylish Designer Studio with Piano,1981742,Daniel,Manhattan,Harlem,40.83091,-73.94223,Entire home/apt,135,5,42,2019-12-10,0.42,1,330
830,399946,Light Superhosted Chill LES Apt,1996265,David,Manhattan,Lower East Side,40.72123,-73.98996,Entire home/apt,80,10,79,2020-08-01,0.78,1,15
831,400039,Big Beautiful Railroad in Brooklyn,1488809,John,Brooklyn,Bushwick,40.70339,-73.92945,Entire home/apt,130,30,53,2017-06-30,0.58,1,0
869,433414,Spacious & Sunny in Prime Brooklyn,287733,David,Brooklyn,Clinton Hill,40.68472,-73.96691,Entire home/apt,99,30,100,2020-07-31,1.01,1,350
903,456110,Beautiful One Bedroom in Chelsea,2267508,Daniel,Manhattan,Chelsea,40.74760,-73.99698,Entire home/apt,139,4,23,2015-10-04,0.23,1,0
905,456457,West Village Gem - 2BR,1594083,David,Manhattan,West Village,40.73204,-74.00189,Entire home/apt,315,3,7,2016-08-29,0.07,1,0
919,467866,"Our NY home, Greenwich Village apt",2321870,David,Manhattan,West Village,40.73123,-74.00591,Private room,100,2,216,2020-02-18,2.16,1,178
943,484297,Large home in most desirable Brooklyn hood!,2397411,John,Brooklyn,Clinton Hill,40.68545,-73.96534,Entire home/apt,375,4,12,2019-08-17,0.12,1,0
947,486350,Great 2 bedroom apartment in Williamsburg!,2407024,Michael,Brooklyn,Williamsburg,40.70821,-73.95352,Entire home/apt,225,7,13,2016-08-21,0.13,2,319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,44081738,Smart & Safe entire home in Staten Island NY,352065598,Daniel,Staten Island,Oakwood,40.56137,-74.10729,Entire home/apt,70,1,1,2020-08-09,1.00,1,256
45590,44088976,"Spacious oasis - office, private garden, parking",1704370,David,Brooklyn,Clinton Hill,40.68574,-73.96126,Entire home/apt,140,3,1,2020-07-25,1.00,1,17
45618,44114508,2 huge bedrooms + private toilet & kitchen,352021160,John,Brooklyn,Crown Heights,40.67155,-73.94618,Private room,75,28,0,NaN,NaN,2,364
45635,44128750,Townhouse Loft By Central Park!,15654886,Michael,Manhattan,Upper West Side,40.79170,-73.96706,Entire home/apt,113,365,0,NaN,NaN,1,359
45636,44131715,Spotless upper east side full 1 bedroom apartment,118744531,Daniel,Manhattan,Upper East Side,40.76865,-73.95250,Entire home/apt,105,3,2,2020-08-01,2.00,1,43
45856,44293422,"Entire, Private East Village Apartment, Sleeps 3",2267153,John,Manhattan,East Village,40.72891,-73.98420,Entire home/apt,141,2,0,NaN,NaN,3,47
45864,44303746,Large 1 bedroom-Flatiron with Elevator/Laundry,89423293,Michael,Manhattan,Chelsea,40.73825,-73.99494,Entire home/apt,125,150,0,NaN,NaN,1,357
45939,44340349,Private Bedroom at a Great Location!!,303446068,John,Manhattan,Upper East Side,40.76150,-73.96198,Private room,81,6,1,2020-07-29,1.00,1,365
45968,44353017,1 bedroom apartment in quiet location,10737943,David,Manhattan,Upper East Side,40.77196,-73.95178,Entire home/apt,62,30,0,NaN,NaN,7,350
46004,44378626,PRIVATE COZY STUDIO,107716952,Michael,Queens,Jamaica,40.69307,-73.80680,Entire home/apt,26,2,0,NaN,NaN,1,229
46011,44381182,Luxury Penthouse with the Best View in Brooklyn,1984312,Daniel,Brooklyn,Boerum Hill,40.68893,-73.98434,Entire home/apt,141,7,0,NaN,NaN,1,19
46043,44406609,Historic Townhouse w/ Private Landscaped Yard,6634085,Michael,Brooklyn,Bedford-Stuyvesant,40.68384,-73.95376,Entire home/apt,110,3,0,NaN,NaN,1,52
46098,44448566,Penthouse apt,38347589,Michael,Manhattan,Hell's Kitchen,40.76740,-73.99255,Entire home/apt,600,1,0,NaN,NaN,1,365
46144,44475210,Bright and Cozy Bedroom in Shared Apt,236572440,David,Manhattan,East Harlem,40.78683,-73.94309,Private room,55,30,0,NaN,NaN,14,365
46149,44475911,Charming Bedroom Bright and Cozy (Shared),236572440,David,Manhattan,East Harlem,40.78703,-73.94415,Private room,53,30,0,NaN,NaN,14,365
46151,44476020,Colorfull and Modern Bedroom (Shared),236572440,David,Manhattan,East Harlem,40.78704,-73.94425,Private room,49,30,0,NaN,NaN,14,365
46152,44476440,Best value double room in New York (Shared),236572440,David,Manhattan,East Harlem,40.78520,-73.94317,Private room,45,30,0,NaN,NaN,14,365
46154,44476634,Best value single room in New York (Shared),236572440,David,Manhattan,East Harlem,40.78481,-73.94372,Private room,45,30,0,NaN,NaN,14,350
46155,44476765,Red Superior double Bedroom (Shared),236572440,David,Manhattan,East Harlem,40.78479,-73.94312,Private room,45,30,0,NaN,NaN,14,365
46183,44491230,cozy two bedroom apartment near the beach,59215768,John,Queens,Rockaway Beach,40.58935,-73.80996,Entire home/apt,179,2,0,NaN,NaN,2,349
46229,44534901,Sunny Sanctuary Room + Prospect Park/Trains,11308947,Michael,Brooklyn,Prospect-Lefferts Gardens,40.65512,-73.96011,Private room,45,1,0,NaN,NaN,2,359
46270,44568305,Hope you feel home here,162021372,Michael,Manhattan,Washington Heights,40.85259,-73.93420,Private room,57,1,0,NaN,NaN,1,365
46326,44609991,"THE ""BUSHWICK EXPERIENCE""- CENTER OF IT ALL!!!",23296177,Daniel,Brooklyn,Bushwick,40.70326,-73.92547,Private room,80,1,0,NaN,NaN,1,90
46332,44615784,Feel at home in the heart of Williamsburg,40999075,John,Brooklyn,Greenpoint,40.71975,-73.95213,Entire home/apt,105,2,0,NaN,NaN,1,13
46350,44631955,Large 1 Bedroom on Upper West Side. Prime Loca...,17070752,David,Manhattan,Upper West Side,40.78744,-73.97571,Entire home/apt,125,7,0,NaN,NaN,1,350
46362,44639591,Central & Stylish 1 Bedroom Apt - Heart of Che...,286136716,John,Manhattan,Chelsea,40.74568,-73.99694,Entire home/apt,110,30,0,NaN,NaN,3,110
46396,44661297,Flushing Sunshine home #101,361579037,Daniel,Queens,Flushing,40.74603,-73.82837,Private room,52,1,0,NaN,NaN,2,360
46403,44662157,Flushing Sunshine home #102,361579037,Daniel,Queens,Flushing,40.74441,-73.82829,Private room,55,1,3,2020-08-16,3.00,2,365
46455,44697211,Davidâ€™s Queen Sized Room,343477029,David,Queens,Far Rockaway,40.59460,-73.75875,Private room,95,1,0,NaN,NaN,1,365
46508,44797527,Long-Term: Furnished Apt in Nolita w/ Amenities,19448640,David,Manhattan,Nolita,40.72289,-73.99400,Entire home/apt,140,30,0,NaN,NaN,1,282

In [14]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 
Williamsburg = df.neighbourhood == 'Williamsburg'

df['adjusted_price'] = np.where(Williamsburg, df.price + 100, df.price)

# df[Williamsburg]
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,adjusted_price
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365,175
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265,75
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365,60
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295,175
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340,65
5,5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.80178,-73.96723,Private room,75,2,118,2017-07-21,0.89,1,0,75
6,5238,Cute & Cozy Lower East Side 1 bdrm,7549,Ben,Manhattan,Chinatown,40.71344,-73.99037,Entire home/apt,140,1,161,2019-07-29,1.21,4,274,140
7,5552,Spacious river view in the West Village,8380,Maria,Manhattan,West Village,40.73552,-74.01042,Entire home/apt,160,3,66,2019-08-10,0.49,1,178,160
8,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,88,4,180,2020-03-18,1.31,3,344,88
9,6021,Wonderful Guest Bedroom in Manhattan CENTRAL PARK,11528,Claudio,Manhattan,Upper West Side,40.79826,-73.96113,Private room,85,2,123,2019-12-09,0.90,1,365,85
10,6090,West Village Nest - Superhost,11975,Alina,Manhattan,West Village,40.73530,-74.00525,Entire home/apt,65,30,29,2020-07-25,0.22,1,197,65
11,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,109,2,181,2020-03-16,1.32,1,0,209
12,6990,UES Beautiful Blue Room / 2 Bedrooms,16800,Cyn,Manhattan,East Harlem,40.78962,-73.94802,Entire home/apt,239,4,233,2019-12-09,1.77,1,365,239
13,7097,Perfect for Your Parents + Garden; Germ-Free,17571,Jane,Brooklyn,Fort Greene,40.69121,-73.97277,Entire home/apt,182,1,229,2020-07-20,1.78,2,325,182
14,7750,2 Furnished bedrooms next to Central Park,17985,Sing,Manhattan,East Harlem,40.79685,-73.94872,Private room,96,14,0,NaN,NaN,2,178,96
15,7801,Sweet and Spacious Brooklyn Loft,21207,Chaya,Brooklyn,Williamsburg,40.71842,-73.95718,Entire home/apt,299,3,9,2011-12-28,0.07,1,337,399
16,8490,"MAISON DES SIRENES1,bohemian apartment",25183,Nathalie,Brooklyn,Bedford-Stuyvesant,40.68371,-73.94028,Entire home/apt,120,2,115,2020-08-13,0.86,2,319,120
17,8505,Sunny Bedroom Across Prospect Park,25326,Gregory,Brooklyn,Windsor Terrace,40.65599,-73.97519,Private room,135,1,23,2019-10-14,0.84,2,89,135
18,8700,Magnifique Suite au N de Manhattan - vue Cloitres,26394,Claude & Sophie,Manhattan,Inwood,40.86754,-73.92639,Private room,86,4,0,NaN,NaN,1,0,86
19,9657,Modern 1 BR / NYC / EAST VILLAGE,21904,Dana,Manhattan,East Village,40.72920,-73.98542,Entire home/apt,220,3,33,2019-11-11,0.25,1,90,220
20,9704,Spacious 1 bedroom in luxe building,32045,Teri,Manhattan,Harlem,40.81305,-73.95466,Private room,55,2,98,2020-03-14,1.30,1,354,55
21,10452,Large B&B Style rooms,35935,Angela,Brooklyn,Bedford-Stuyvesant,40.68310,-73.95473,Private room,70,3,75,2019-10-12,0.60,2,365,70
22,10962,"Lovely Room 2; Garden; Best area, Legal",9744,Laurie,Brooklyn,South Slope,40.66869,-73.98780,Private room,88,4,180,2020-08-03,1.36,3,365,88
23,11943,Country space in the city,45445,Harriet,Brooklyn,Flatbush,40.63702,-73.96327,Private room,150,1,0,NaN,NaN,1,365,150
24,12048,LowerEastSide apt share shortterm 1,7549,Ben,Manhattan,Lower East Side,40.71401,-73.98917,Shared room,40,1,219,2019-11-13,1.67,4,226,40
25,12192,ENJOY Downtown NYC!,46978,Edward,Manhattan,East Village,40.72290,-73.98199,Private room,40,2,262,2020-03-17,1.99,2,46,40
26,12343,BEST BET IN HARLEM,47727,Earl,Manhattan,Harlem,40.81175,-73.94478,Entire home/apt,150,7,107,2019-12-07,0.83,1,364,150
27,12627,Entire apartment in central Brooklyn neighborh...,49670,Rana,Brooklyn,Prospect-Lefferts Gardens,40.65944,-73.96238,Entire home/apt,95,30,13,2019-12-05,0.36,1,156,95
28,12937,"1 Stop fr. Manhattan! Private Suite,Landmark B...",50124,Orestes,Queens,Long Island City,40.74771,-73.94740,Private room,130,2,280,2020-03-15,2.26,1,246,130
29,12940,Charming Brownstone 3 - Near PRATT,50148,Adreinne,Brooklyn,Bedford-Stuyvesant,40.68111,-73.95591,Entire home/apt,100,5,66,2020-03-02,0.51,1,19,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46497,44767959,A very quiet and crime free neighborhood,289154444,Olu,Queens,Rosedale,40.65192,-73.74515,Private room,70,1,0,NaN,NaN,2,139,70
46498,44768081,Home is where the heart is . Sharing mine with...,215027230,Caron,Bronx,Wakefield,40.88655,-73.86012,Private room,152,2,0,NaN,NaN,1,354,152
46499,44769471,Luxury 2 Bedroom 2 Bath Townhouse in Manhattan,1556814,Tammy,Manhattan,Harlem,40.81543,-73.94143,Entire home/apt,250,5,0,NaN,NaN,7,364,250
46500,44770013,Luxury Building. Panoramic Views!,17532419,Elena,Manhattan,Murray Hill,40.74541,-73.97361,Entire home/apt,381,4,0,NaN,NaN,1,360,381
46501,44789250,Private Room Chelsea 4A,241889662,Incentra Village Hotel,Manhattan,Chelsea,40.75049,-73.99528,Private room,62,1,0,NaN,NaN,36,364,62
46502,44789815,Private Room Chelsea 3D,241889662,Incentra Village Hotel,Manhattan,Chelsea,40.74834,-73.99656,Private room,62,1,0,NaN,NaN,36,362,62
46503,44790395,Private Room Chelsea 2D,241889662,Incentra Village Hotel,Manhattan,Chelsea,40.74922,-73.99714,Private room,62,1,0,NaN,NaN,36,365,62
46504,44791688,1 bdrm apt. on Orchard and Broome LES,8737911,Laura,Manhattan,Chinatown,40.71702,-73.99069,Entire home/apt,124,1,0,NaN,NaN,1,321,124
46505,44791984,very convenient area right next to JMZ train,86766592,Gabby,Brooklyn,Bushwick,40.69874,-73.93696,Private room,96,1,0,NaN,NaN,1,174,96
46506,44792997,The Best of the Upper Westside,362369539,Siobhan,Manhattan,Upper West Side,40.79261,-73.97671,Entire home/apt,400,4,0,NaN,NaN,1,4,400
46507,44795562,Spacious Brooklyn Home with Private Roofdeck,4035493,Jessica,Brooklyn,Vinegar Hill,40.70358,-73.98217,Private room,201,5,0,NaN,NaN,1,45,201
46508,44797527,Long-Term: Furnished Apt in Nolita w/ Amenities,19448640,David,Manhattan,Nolita,40.72289,-73.99400,Entire home/apt,140,30,0,NaN,NaN,1,282,140
46509,44798678,Sonder *Private 1BR Apartment* at Battery Park,219517861,Sonder (NYC),Manhattan,Financial District,40.70454,-74.01647,Entire home/apt,1806,2,0,NaN,NaN,43,337,1806
46510,44798876,Unique & beautiful design! Skylights-Washer/dryer,143513836,Elisabeth,Brooklyn,Crown Heights,40.67156,-73.91651,Private room,61,30,0,NaN,NaN,5,329,61
46511,44799007,Sonder at Battery Park | Studio with Weekly Di...,219517861,Sonder (NYC),Manhattan,Financial District,40.70439,-74.01470,Entire home/apt,1806,2,0,NaN,NaN,43,337,1806
46512,44799074,Sonder *Weekly Discounts* ADA Studio at Batter...,219517861,Sonder (NYC),Manhattan,Financial District,40.70469,-74.01473,Entire home/apt,169,2,0,NaN,NaN,43,337,169
46513,44800276,"Williamsburg 1 Bedroom, Spacious and Classy",361034257,Angelo + Amirah,Brooklyn,Williamsburg,40.71283,-73.95400,Entire home/apt,180,7,0,NaN,NaN,1,364,280
46514,44801333,Like a home,244745075,Tamar,Queens,Rego Park,40.71973,-73.86140,Private room,45,7,0,NaN,NaN,1,359,45
46515,44801335,Bright & Cozy Nolita 1 Bedroom,361814116,Lorena & Mario,Manhattan,Nolita,40.72035,-73.99436,Entire home/apt,175,7,0,NaN,NaN,1,364,175
46516,44801958,Luxury building apartment in FiDi Manhattan,82696573,Kendall,Manhattan,Financial District,40.70629,-74.00588,Private room,60,120,0,NaN,NaN,1,349,60
46517,44802032,A very large room in Williamsburg,213793805,Omer,Brooklyn,Williamsburg,40.71970,-73.95632,Private room,55,14,0,NaN,NaN,1,45,155
46518,44802224,Unique & beautiful design! Skylights-Washer/dryer,143513836,Elisabeth,Brooklyn,Crown Heights,40.67302,-73.91695,Private room,61,30,0,NaN,NaN,5,363,61
46519,44803201,1200 SF Duplex apt in an old shoe factory/ mon...,921746,Michael + JosuÃ©,Brooklyn,Clinton Hill,40.69034,-73.96179,Entire home/apt,253,30,0,NaN,NaN,1,74,253
46520,44804690,"Cozy place, peaceful, friendly and affordable.",362419479,Elia,Queens,St. Albans,40.69980,-73.77104,Private room,44,1,0,NaN,NaN,1,161,44
46521,44807338,Modern luxury Chelsea one bedroom,36370873,Ashley,Manhattan,Chelsea,40.74698,-73.99512,Entire home/apt,140,7,0,NaN,NaN,1,358,140
46522,44807522,Designer Gramercy Studio Townhouse by UNSQ,12941925,Brian,Manhattan,Gramercy,40.73433,-73.98383,Entire home/apt,145,7,0,NaN,NaN,1,164,145
46523,44807786,Cozy & comfy apt in the heart of Inwood Manhattan,284790520,Salar,Manhattan,Washington Heights,40.85820,-73.92733,Entire home/apt,87,6,0,NaN,NaN,2,85,87
46524,44811717,Comfortable safe environment 24hr security camera,362453686,Nicole,Brooklyn,East Flatbush,40.65399,-73.93287,Private room,59,3,0,NaN,NaN,1,90,59
46525,44814944,Upper West Side studio 86th Street,4039777,Fernando,Manhattan,Upper West Side,40.78731,-73.97029,Entire home/apt,80,30,0,NaN,NaN,1,113,80
46526,44818009,"5MIN D/N trains, NEAR THE BEACH, 50â€™ TO MANHATTAN",48098268,Marina,Brooklyn,Gravesend,40.59945,-73.98209,Private room,66,1,0,NaN,NaN,1,38,66

In [15]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  
dfp = df.room_type.value_counts() / df.room_type.value_counts().sum()
# dfp
dfp.iloc[[1,2]]

Private room    0.454446
Shared room     0.021213
Name: room_type, dtype: float64

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [17]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.
listings_group = df.groupby('neighbourhood_group').count()
listings_group.calculated_host_listings_count

neighbourhood_group
Bronx             1183
Brooklyn         18632
Manhattan        20580
Queens            5791
Staten Island      341
Name: calculated_host_listings_count, dtype: int64

In [34]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 
meanprice = df.groupby('neighbourhood_group')['price'].mean()
meanprice

KeyError: 'Column not found: price'

In [33]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 
minmax = df.groupby('neighbourhood_group')['price'].agg(['min', 'max'])
minmax

KeyError: 'Column not found: price'

In [32]:
# 4. Using `groupby`, find the mean price for each room type in each neighbourhood_group.
meanroomprice = df.groupby('room_type')['price'].mean()
meanroomprice

KeyError: 'room_type'

In [31]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.
aggroom = df.groupby(['neighbourhood_group', 'room_type'])['price'].agg(['count', 'min', 'max', 'mean', 'median', 'std'])
aggroom

KeyError: 'room_type'

# Join and file saving.
1. Load the `prices.csv` and the `n_listings.csv`


2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']
       
       
3. Save your joined csv as `joined.csv`


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [23]:
# 1. Load the `prices.csv` and the `n_listings.csv`
pr = pd.read_csv('data/prices.csv', sep=',')
nl = pd.read_csv('data/n_listings.csv', sep=';')
nl.head()
# pr.head()

  neighbourhood_group  n_listings
0               Bronx        1183
1            Brooklyn       18632
2           Manhattan       20580
3          LongIsland        4121

In [24]:
# 2. Do join that keeps all the records for each table.
df = pd.merge(pr, nl, how="outer")

save_as = 'prices-n_listings.csv'
df.to_csv(save_as, index=False)

# Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

In [25]:
#  1. Who was won Album of the Year in 2016?
gr = pd.read_csv('data/grammys.csv')
AlbumofYear = gr.category == 'Album of the Year' 
Winner = gr.winner
year2016 = gr.year == 2016
gr[AlbumofYear & Winner & year2016].workers

5505    Taylor Swift (artist/producer), Jack Antonoff ...
Name: workers, dtype: object

In [26]:
# 2. Who won Best Rap Album in 2009?
BestRapAlbum = gr.category == 'Best Rap Album' 
year2009 = gr.year == 2009
gr[BestRapAlbum & Winner & year2009].workers

4396    Lil' Wayne
Name: workers, dtype: object

In [29]:
# 3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?
KendrickLamar = gr.workers == 'Kendrick Lamar'
gr[KendrickLamar]
#gr[Winner & KendrickLamar].category.count()

,year,category,nominee,workers,winner
5269,2014,Best Rap Album,"Good Kid, M.A.A.D City.",Kendrick Lamar,False
5272,2014,Best Rap Performance,Swimming Pools (Drank).,Kendrick Lamar,False
5448,2015,Best Rap Performance,i.,Kendrick Lamar,True
5596,2016,Best Rap Album,To Pimp a Butterfly.,Kendrick Lamar,True
5599,2016,Best Rap Performance,Alright.,Kendrick Lamar,True
6003,2018,Best Rap Performance,HUMBLE.,Kendrick Lamar,True